set_property PACKAGE_PIN V10 [get_ports en_rd]
set_property PACKAGE_PIN U11 [get_ports rst_wr]
set_property PACKAGE_PIN V12 [get_ports en_wr]
set_property PACKAGE_PIN U12 [get_ports rst_rd]
set_property PACKAGE_PIN T15 [get_ports full]
set_property PACKAGE_PIN U13 [get_ports {din[3]}]
set_property PACKAGE_PIN V11 [get_ports {din[7]}]
set_property PACKAGE_PIN U14 [get_ports {din[6]}]
set_property PACKAGE_PIN V14 [get_ports {din[5]}]
set_property PACKAGE_PIN V17 [get_ports {dout[1]}]
set_property PACKAGE_PIN T13 [get_ports {din[4]}]
set_property PACKAGE_PIN U17 [get_ports {dout[4]}]
set_property PACKAGE_PIN T9 [get_ports {din[2]}]
set_property PACKAGE_PIN T10 [get_ports {din[1]}]
set_property PACKAGE_PIN U16 [get_ports {dout[2]}]
set_property PACKAGE_PIN T11 [get_ports {dout[0]}]
set_property PACKAGE_PIN V16 [get_ports {dout[5]}]
set_property PACKAGE_PIN U18 [get_ports {dout[3]}]
set_property PACKAGE_PIN R10 [get_ports {din[0]}]
set_property PACKAGE_PIN T16 [get_ports {dout[7]}]
set_property PACKAGE_PIN N15 [get_ports clk_rd]
set_property PACKAGE_PIN R16 [get_ports empty]
set_property PACKAGE_PIN T14 [get_ports clk_wr]
set_property PACKAGE_PIN V15 [get_ports {dout[6]}]

create_clock -period 10.000 -waveform {0.000 5.000} [get_ports clk_wr]
create_clock -period 7.500 -waveform {0.000 3.750} [get_ports clk_rd]

set_clock_groups -asynchronous -group [get_clocks clk_wr] -group [get_clocks clk_rd]
